### PR TITLE
dec-2018-testfix Windows 2008/2008 R2 SQL 2008/2008 R2 EOS planning

### PR DESCRIPTION
**Pull request by paulopsgility**

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Hi Paul,
Please verify this update addresses open issue #13 
Thanks,
Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Hi Paul,
I was looking at previous email chains for this one.  We need a good review of the alt-text for this workshop.  More detail is needed in many of the images.
Thank you!  Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
From Sue Hartford via email on 1/3:

A few comments from the Windows Server side:
•	Nothing has changed dramatically since the summer, so no inaccuracies.
•	Abstract and content: can we introduce a section on “how to upgrade on-premises” for those workloads that cannot migrate to Azure? It does not need to be comprehensive.  The Windows Server upgrade guidance is here.
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows-server%2Fget-started%2Fmodernize-windows-server-2008&data=02%7C01%7Cv-dadesj%40microsoft.com%7C933bb676ea9642caaa0e08d6719aab0f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636821306436597856&sdata=iJRwxGcCVonvKu9Brzn61OvSUXd%2FFqIeanROoMUX5Fs%3D&reserved=0
•	I see you have a Trainer link to the database Azure Hero Solution. You can also add a link to the Windows Server on Azure hero solution.
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fteams%2FGearUp%2FSitePages%2Fazureherosolutions.aspx&data=02%7C01%7Cv-dadesj%40microsoft.com%7C933bb676ea9642caaa0e08d6719aab0f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636821306436637884&sdata=BXly7GPWM%2B3C6FFRFZSbBOEj%2FDDUl7KsMjuk9xcatYI%3D&reserved=0
•	The current Trainer doc introduces Azure Cost Management early in the process, when I think customers may actually be looking for the Azure pricing calculator and TCO calculator – both can help the customer understand their costs to run in Azure before moving forward.
•	Resources: We have dedicated pages for Windows Server and SQL Server on the Azure Migration Center.
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Fmigration%2Fwindows-server%2F&data=02%7C01%7Cv-dadesj%40microsoft.com%7C933bb676ea9642caaa0e08d6719aab0f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636821306436647894&sdata=q0KQ28%2FhuTpbXaBTzVvu8UrKLIGw6%2FhUAcYqnoUBzY8%3D&reserved=0
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Fmigration%2Fsql-server%2F&data=02%7C01%7Cv-dadesj%40microsoft.com%7C933bb676ea9642caaa0e08d6719aab0f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636821306436647894&sdata=Z%2FyAh1u4DjUTNvjjjSAmELEk%2FK0qSzPj6VM86EtSzAw%3D&reserved=0
•	Resources: Please add the Windows Server Migration Guide
https://go.microsoft.com/fwlink/?linkid=872689

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility @mwasham 
Hi gentlemen,  
We have sign-off from both of the tech leads to finalize this update.  Please make any final changed, close any open issues and send to your editors.  Let me know when it's ready for me to QC/merge.
Thanks, Dawnmarie

**Comment by Jeff-Opsgility** [comment]
@paulopsgility , can we get a final review please.  Once complete, please assign to me and I'll let Dawnmarie know.  Thank you.

**Pull request merged**
